<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        .box {
            width: 40%;
            margin: 0 auto;
            background: rgba(255, 255, 255, 0.2);
            padding: 35px;
            border: 2px solid #fff;
            border-radius: 20px/50px;
            background-clip: padding-box;
            text-align: center;
        }

        .overlay {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(0, 0, 0, 0.7);
            transition: opacity 500ms;
            visibility: hidden;
            opacity: 0;
        }

        .overlay:target {
            visibility: visible;
            opacity: 1;
        }

        .popup {
            margin: 70px auto;
            padding: 20px;
            background: #fff;
            border-radius: 5px;
            width: 30%;
            position: relative;
            transition: all 5s ease-in-out;
        }

        .popup h2 {
            margin-top: 0;
            color: #333;
            font-family: Tahoma, Arial, sans-serif;
        }

        .popup .close {
            position: absolute;
            top: 20px;
            right: 30px;
            transition: all 200ms;
            font-size: 30px;
            font-weight: bold;
            text-decoration: none;
            color: #333;
        }

        .popup .close:hover {
            color: #06D85F;
        }

        .popup .content {
            max-height: 30%;
            overflow: auto;
        }

        @media screen and (max-width: 700px) {
            .box {
                width: 70%;
            }

            .popup {
                width: 70%;
            }
        }
    </style>
</head>

<body>
    <h2>Search Collections</h2>
    <form method="POST" action="/login/listProducts">
        <input type="text" placeholder="Search.." name="searchList">
        <input type="submit" name="search" value="Search">
    </form>
    <!-- <table>
        <tr>
            <thead class="thead-dark">
                <th>Product Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Stock</th>
            </thead>
        </tr>
        <?php if ($allResult) { ?>
            <?php foreach ($allResult as $k => $v) { ?>
                <tr>
                    <td>
                        <input type="text" value=<?php echo $v->name; ?>>
                    </td>
                    <td>
                        <input type="text" value=<?php echo $v->category; ?>>
                    </td>
                    <td>
                        <input type="number" value=<?php echo $v->price; ?>>
                    </td>
                    <td>
                        <input type="number" value=<?php echo $v->stock; ?>>
                    </td> -->
    <!-- <td>
                        <button class="btn btn-dark" data-toggle="modal" data-target="#myModal">Quick View</button>
                    </td> -->
    <!-- </tr>
        <?php
            }
        } ?>
    </table> -->
    <?php
    if ($result) { ?>
        <tr>
            <table>

                <thead class="thead-dark">
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Stock</th>
                </thead>
        </tr>

        <?php foreach ($result as $k => $v) { ?>
            <form action="/login/updateList" method="POST">
                <tr>
                    <td>
                        <input type="text" value="<?php echo $v->name; ?>">
                    </td>
                    <td>
                        <input type="text" value="<?php echo $v->category; ?>">
                    </td>
                    <td>
                        <input type="number" value="<?php echo $v->price; ?>">
                    </td>
                    <td>
                        <input type="number" value="<?php echo $v->stock; ?>">
                    </td>
                    <!-- <form action="/login/popup"> -->
                    <td>
                        <a class='btn btn-primary' href=#<?php echo $v->_id ?>>Quick view</a>
                    </td>
                    <td>
                        <!-- <form action="login/updateList" method="POST"> -->
                        <input type="hidden" name="id" value=<?php echo $v->_id ?>>
                        <input type="submit" name="edit" class="btn btn-primary" value="Edit">

                    </td>
                    <!-- </form> -->
                    <td>
                        <input type="submit" name="delete" class="btn btn-danger" value="Delete">

                        

            </form>
            </tr>
            <div id="<?php echo $v->_id; ?>" class="overlay">
                            <div class="popup">
                                <h3 class="text-center"><?php echo $v->name; ?></h3><br>
                                <a class="close" href="#">&times;</a>
                                <div class="content">
                                    <h5>Additional Fields</h5>
                                    <?php if ($v->added_fields) {
                                        foreach ($v->added_fields as $k2 => $v2) {
                                            echo $k2 . ' : ' . $v2 . '<br>';
                                        }
                                    } ?>
                                </div>
                            </div>
                        </div>
    <?php
        }
    } else {
        echo "No result found!!";
    } ?>
    </table>




</body>

</html>
<!-- <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Category</th> -->
<!-- <th scope="col">Name</th> -->
<!-- <th scope="col">Price</th>
                                <th scope="col">Stock</th>
                                <th scope="col">View</th> -->
<!-- <th scope="col">Status</th> -->
<!-- <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                             <?php
                                //var_dump($data)[0];
                                foreach ($products as $k => $v) {
                                    echo '<form method="POST" action="/dashboard/status">
                                <tr><td>' . $v->name . '</td>
                                <td>' . $v->category . '</td>
                                <td>' . $v->price . '</td>
                                <td>' . $v->stock . '</td>
                                <td><a href = "" >Quick View</a></td>
                                <td><a href=delete?id=' . $v->_id . ' class="btn btn-danger">Delete</a></td>
                                <td><a href=edit?id=' . $v->_id . ' class="btn btn-primary">Edit</a></tr></form>';
                                }


                                ?>

                        </tbody>
                    </table> -->