<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="/order/index" method="POST">
<label for="color">Choose Product:</label>
<select name="product_name" id="product_name">
    <option value="">--- Choose a product ---</option>
    <?php foreach($place as $k => $v ) { ?> 
    <option value="<?php echo $v->name?>"><?php echo $v->name; ?> </option>
    <?php } ?>
	<!-- <option value="">--- Choose a product ---</option>
	<option value="red">Red</option>
	<option value="green">Green</option>
	<option value="blue">Blue</option> -->
</select>
<br>
<label for="customer_name">Customer Name</label>
<input type="text" name="name" id="name" placeholder="Enter Customer Name">
<br>
<label for="customer_quantity">Quantity</label>
<input type="number" name="number" id="number" placeholder="Enter Quantity">
<br><br>
  <input type="submit" class="btn btn-success" name="submit" value="Submit">  
</form>
<br>
<form action="/order/listOrders" method="POST">

<input type="submit" class="btn btn-primary" name="order" value = "Show Products">
</form>
</body>
</html>